#!/usr/bin/env python3
"""Regenerate the shared static encoding/newline fixtures used by the JVM tests.

Why a generator instead of runtime-generated data:
  The desktop Go tests (`mdview/app_test.go:91-185`) build their byte inputs at
  test time. The plan requires the Android equivalence claim to be bounded to a
  *shared, static* fixture corpus, so the bytes are frozen here and committed as
  `android/app/src/test/resources/encoding/*.json`.

The generator is deterministic: no timestamps, stable key order, `json.dump`
with `sort_keys=True` and a trailing newline. Re-running it with the same Python
produces byte-identical files (verify with `git diff --stat`).

Usage:
  python3 android/tools/generate-encoding-fixtures.py

Outputs (relative to the repo root):
  android/app/src/test/resources/encoding/encoding-fixtures.json
  android/app/src/test/resources/encoding/newline-fixtures.json

The fixture schema is consumed by `EncodingTest.kt` / `NewlineTest.kt`:
  encoding case: name, bytesHex, expectedEncoding, expectedContent,
                 expectRoundTrip, (optional) expectEncodeReject, unmappableSuffix
  newline case:  name, text, expected
  apply case:    name, content, newline, expected
"""

import json
import os

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RES_DIR = os.path.join(REPO_ROOT, "android", "app", "src", "test", "resources", "encoding")


def latin1_text(data: bytes) -> str:
    """Byte-fidelity mapping used by the port: byte -> same-value codepoint."""
    return data.decode("latin-1")


def build_encoding_fixtures() -> dict:
    gb_source = (
        "# 测试文档\n\n"
        "这是一段简体中文内容，用于验证 GB18030 编码的检测、解码与回写是否无损。"
        "包含公式 $x^2+y^2=z^2$ 与图片 ![](images/figure-1.jpg)。\n"
    )
    gb_bytes = gb_source.encode("gb18030")

    big5_source = (
        "這是一段繁體中文測試文字，用來驗證 Big5 編碼的偵測、解碼與回寫是否正確無損。\n"
    )
    big5_bytes = big5_source.encode("big5")

    # Mirrors the Go binary fixture shape (PNG magic + NUL + 0xFE/0xFF noise);
    # the NUL byte must keep both CJK probes off (app.go:471/:479).
    binary = bytes([0x89, ord("P"), ord("N"), ord("G"), 0x00, 0x01, 0x02, 0xFE, 0xFF])
    binary += bytes([0xAB, 0xCD, 0x00, 0x11]) * 64

    cases = [
        # --- the four discriminating fixtures (plan acceptance) ---
        {
            "name": "valid-utf8-cafe",
            "bytesHex": "636166c3a9",
            "expectedEncoding": "utf-8",
            "expectedContent": "café",
            "expectRoundTrip": True,
        },
        {
            "name": "invalid-utf8-single-byte-e9",
            "bytesHex": "e9",
            "expectedEncoding": "iso-8859-1",
            "expectedContent": "é",
            "expectRoundTrip": True,
        },
        {
            "name": "nul-containing-binary",
            "bytesHex": binary.hex(),
            "expectedEncoding": "iso-8859-1",
            "expectedContent": latin1_text(binary),
            "expectRoundTrip": True,
        },
        {
            "name": "byte-fidelity-unmappable-suffix",
            "bytesHex": "e9",
            "expectedEncoding": "iso-8859-1",
            "expectedContent": "é",
            "expectRoundTrip": True,
            "unmappableSuffix": "中",
            "expectEncodeReject": True,
        },
        # --- CJK round-trips (JVM corpus; [device] round-trip still deferred) ---
        {
            "name": "gb18030-simplified-chinese",
            "bytesHex": gb_bytes.hex(),
            "expectedEncoding": "gb18030",
            "expectedContent": gb_source,
            "expectRoundTrip": True,
        },
        {
            "name": "big5-traditional-chinese",
            "bytesHex": big5_bytes.hex(),
            "expectedEncoding": "big5",
            "expectedContent": big5_source,
            "expectRoundTrip": True,
        },
        # --- adversarial: malformed/truncated must fall back byte-for-byte ---
        {
            "name": "malformed-gb18030-incomplete-4byte",
            "bytesHex": "8130",
            "expectedEncoding": "iso-8859-1",
            "expectedContent": latin1_text(bytes([0x81, 0x30])),
            "expectRoundTrip": True,
        },
        {
            "name": "truncated-big5-lead-byte",
            "bytesHex": "a4",
            "expectedEncoding": "iso-8859-1",
            "expectedContent": latin1_text(bytes([0xA4])),
            "expectRoundTrip": True,
        },
    ]

    return {
        "note": "Generated by android/tools/generate-encoding-fixtures.py. Do not hand-edit.",
        "cases": cases,
    }


def build_newline_fixtures() -> dict:
    return {
        "note": "Generated by android/tools/generate-encoding-fixtures.py. Do not hand-edit.",
        "cases": [
            {"name": "crlf-dominant", "text": "a\r\nb\r\n", "expected": "crlf"},
            {"name": "lf-only", "text": "a\nb\n", "expected": "lf"},
            # An LF file with one stray CRLF keeps LF (majority wins).
            {"name": "lf-with-one-stray-crlf", "text": "a\nb\nc\r\nd\n", "expected": "lf"},
            {"name": "crlf-dominant-mixed", "text": "a\r\nb\r\nc\nd\r\n", "expected": "crlf"},
            # Equal counts: the tie must go to LF.
            {"name": "tie-goes-to-lf", "text": "a\r\nb\n", "expected": "lf"},
            {"name": "empty-file", "text": "", "expected": "lf"},
        ],
        "applyCases": [
            {"name": "crlf-expansion", "content": "a\r\nb\nc", "newline": "crlf", "expected": "a\r\nb\r\nc"},
            {"name": "lf-passthrough", "content": "a\nb\nc", "newline": "lf", "expected": "a\nb\nc"},
            {"name": "unknown-newline-passthrough", "content": "a\nb", "newline": "other", "expected": "a\nb"},
        ],
    }


def write_json(name: str, payload: dict) -> None:
    os.makedirs(RES_DIR, exist_ok=True)
    path = os.path.join(RES_DIR, name)
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2, sort_keys=True)
        handle.write("\n")
    print("wrote", os.path.relpath(path, REPO_ROOT))


def main() -> None:
    write_json("encoding-fixtures.json", build_encoding_fixtures())
    write_json("newline-fixtures.json", build_newline_fixtures())


if __name__ == "__main__":
    main()
