// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function ClearDraft(arg1:string):Promise<void>;

export function ClearRecents():Promise<void>;

export function ConfirmExit():Promise<void>;

export function GetRecents():Promise<Array<string>>;

export function GetStartupFile():Promise<string>;

export function ListDrafts():Promise<Array<main.DraftInfo>>;

export function LoadDraft(arg1:string):Promise<string>;

export function LoadImageForSrc(arg1:string,arg2:string,arg3:string):Promise<main.ImageData>;

export function OpenFile():Promise<main.OpenResult>;

export function PickSavePath(arg1:string):Promise<string>;

export function ReadFileAt(arg1:string):Promise<main.OpenResult>;

export function RemoveRecent(arg1:string):Promise<void>;

export function SaveDraft(arg1:string,arg2:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetDirty(arg1:boolean):Promise<void>;

export function SetStartupArgs(arg1:Array<string>):Promise<void>;

export function SetTitle(arg1:string):Promise<void>;
