// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConfirmExit():Promise<void>;

export function GetRecents():Promise<Array<string>>;

export function LoadImageForSrc(arg1:string,arg2:string,arg3:string):Promise<main.ImageData>;

export function OpenFile():Promise<main.OpenResult>;

export function ReadFileAt(arg1:string):Promise<main.OpenResult>;

export function RemoveRecent(arg1:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetDirty(arg1:boolean):Promise<void>;

export function SetTitle(arg1:string):Promise<void>;
