package io.github.koucpy001.simplify2md.encoding

import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test

/**
 * Pure-JVM equivalence tests for the encoding port (plan todo 9).
 *
 * The corpus is the shared static fixture file generated by
 * `android/tools/generate-encoding-fixtures.py` (path recorded in the todo 9
 * evidence file). Every case asserts the full detect -> decode -> encode chain:
 *   detectEncoding(bytes) == expectedEncoding
 *   decodeBytes(bytes, expectedEncoding) == expectedContent
 *   encodeContent(expectedContent, expectedEncoding) == bytes   (round-trip)
 *
 * The codec under test is `encoding/Encoding.kt`, which uses only JDK charsets
 * and runs under plain JUnit (no Android test framework, no third-party
 * charset library).
 */
class EncodingTest {

    private fun fixtures(): JSONArray {
        val stream = requireNotNull(
            EncodingTest::class.java.getResourceAsStream("/encoding/encoding-fixtures.json"),
        ) { "missing fixture resource /encoding/encoding-fixtures.json" }
        val text = String(stream.readAllBytes(), Charsets.UTF_8)
        return JSONObject(text).getJSONArray("cases")
    }

    private fun hexToBytes(hex: String): ByteArray {
        val out = ByteArray(hex.length / 2)
        for (i in out.indices) {
            out[i] = hex.substring(i * 2, i * 2 + 2).toInt(16).toByte()
        }
        return out
    }

    @Test
    fun everyFixtureDetectsDecodesAndRoundTrips() {
        val cases = fixtures()
        assertTrue("fixture corpus must not be empty", cases.length() > 0)
        for (i in 0 until cases.length()) {
            val c = cases.getJSONObject(i)
            val name = c.getString("name")
            val bytes = hexToBytes(c.getString("bytesHex"))
            val expectedEncoding = c.getString("expectedEncoding")
            val expectedContent = c.getString("expectedContent")

            assertEquals("[$name] detectEncoding", expectedEncoding, EncodingCodec.detectEncoding(bytes))
            assertEquals("[$name] decodeBytes", expectedContent, EncodingCodec.decodeBytes(bytes, expectedEncoding))

            if (c.optBoolean("expectRoundTrip", false)) {
                val reencoded = EncodingCodec.encodeContent(expectedContent, expectedEncoding)
                assertArrayEquals("[$name] encode(decode(b)) must equal b", bytes, reencoded)
            }
        }
    }

    @Test
    fun unmappableCodepointIsReportedNeverReplaced() {
        // Fixture (iv): typing a non-Latin-1 codepoint into a byte-fidelity
        // document must REPORT/reject with the stable token, never write '?'.
        val cases = fixtures()
        var checked = 0
        for (i in 0 until cases.length()) {
            val c = cases.getJSONObject(i)
            if (!c.optBoolean("expectEncodeReject", false)) continue
            checked++
            val name = c.getString("name")
            val suffix = c.getString("unmappableSuffix")
            val content = c.getString("expectedContent") + suffix
            val encoding = c.getString("expectedEncoding")
            try {
                EncodingCodec.encodeContent(content, encoding)
                fail("[$name] encode must reject unmappable content, not silently write '?'")
            } catch (e: EncodingCodec.EncodingException) {
                assertEquals("[$name] reject must carry the stable token", EncodingCodec.UNMAPPABLE_TOKEN, e.token)
                assertTrue("[$name] message must contain the token", e.message!!.contains(EncodingCodec.UNMAPPABLE_TOKEN))
            }
        }
        assertTrue("at least one unmappable fixture must exist", checked > 0)
    }

    @Test
    fun unknownEncodingLabelIsRejectedOnEncode() {
        // Arbitrary labels crossing the bridge are untrusted input: an unknown
        // label must never be silently written as UTF-8 (the Go default branch).
        try {
            EncodingCodec.encodeContent("hello", "x-user-defined")
            fail("unknown label must be rejected")
        } catch (e: EncodingCodec.EncodingException) {
            assertEquals(EncodingCodec.UNKNOWN_LABEL_TOKEN, e.token)
        }
    }

    @Test
    fun unknownEncodingLabelFallsBackToByteFidelityOnDecode() {
        // decodeBytes with an unknown label returns the byte-fidelity mapping
        // (byte -> same codepoint), never U+FFFD.
        val bytes = byteArrayOf(0xE9.toByte(), 0x41)
        assertEquals("\u00E9A", EncodingCodec.decodeBytes(bytes, "x-user-defined"))
    }

    @Test
    fun invalidUtf8UnderUtf8LabelFallsBackWithoutUfffd() {
        // Defensive: a "utf-8" label paired with invalid bytes must not insert
        // U+FFFD; the byte-fidelity mapping keeps every byte recoverable.
        val bytes = byteArrayOf(0xE9.toByte())
        val decoded = EncodingCodec.decodeBytes(bytes, EncodingCodec.UTF_8)
        assertEquals("\u00E9", decoded)
        assertFalse("no U+FFFD may be inserted", decoded.contains('\uFFFD'))
    }

    @Test
    fun containsCjkMatchesTheGoRanges() {
        assertTrue(EncodingCodec.containsCJK("\u3400"))
        assertTrue(EncodingCodec.containsCJK("\u9FFF"))
        assertTrue(EncodingCodec.containsCJK("\uF900"))
        assertTrue(EncodingCodec.containsCJK("\uFAFF"))
        assertTrue(EncodingCodec.containsCJK("abc\u4E2D"))
        assertFalse(EncodingCodec.containsCJK("plain ascii"))
        assertFalse(EncodingCodec.containsCJK("\u3000\uFF01")) // CJK punctuation is outside the ranges
        assertFalse(EncodingCodec.containsCJK(""))
    }

    @Test
    fun decodeCombinedFunctionKeepsLabelAndContentConsistent() {
        // detect-then-decode must return a self-consistent pair: the label that
        // produced the content, so a later save cannot corrupt the file.
        val cafe = hexToBytes("636166c3a9")
        val d1 = EncodingCodec.decode(cafe)
        assertEquals(EncodingCodec.UTF_8, d1.encoding)
        assertEquals("café", d1.content)

        val lone = hexToBytes("e9")
        val d2 = EncodingCodec.decode(lone)
        assertEquals(EncodingCodec.ISO_8859_1, d2.encoding)
        assertEquals("\u00E9", d2.content)
    }
}