package io.github.koucpy001.simplify2md.encoding

import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test

/**
 * Pure-JVM equivalence tests for the encoding port (plan todo 9).
 *
 * The corpus is the shared static fixture file generated by
 * `android/tools/generate-encoding-fixtures.py` (path recorded in the todo 9
 * evidence file). Every case asserts the full detect -> decode -> encode chain:
 *   detectEncoding(bytes) == expectedEncoding
 *   decodeBytes(bytes, expectedEncoding) == expectedContent
 *   encodeContent(expectedContent, expectedEncoding) == bytes   (round-trip)
 *
 * The codec under test is `encoding/Encoding.kt`, which uses only JDK charsets
 * and runs under plain JUnit (no Android test framework, no third-party
 * charset library).
 */
class EncodingTest {

    private fun fixtures(): JSONArray {
        val stream = requireNotNull(
            EncodingTest::class.java.getResourceAsStream("/encoding/encoding-fixtures.json"),
        ) { "missing fixture resource /encoding/encoding-fixtures.json" }
        val text = String(stream.readAllBytes(), Charsets.UTF_8)
        return JSONObject(text).getJSONArray("cases")
    }

    private fun hexToBytes(hex: String): ByteArray {
        val out = ByteArray(hex.length / 2)
        for (i in out.indices) {
            out[i] = hex.substring(i * 2, i * 2 + 2).toInt(16).toByte()
        }
        return out
    }

    @Test
    fun everyFixtureDetectsDecodesAndRoundTrips() {
        val cases = fixtures()
        assertTrue("fixture corpus must not be empty", cases.length() > 0)
        for (i in 0 until cases.length()) {
            val c = cases.getJSONObject(i)
            val name = c.getString("name")
            val bytes = hexToBytes(c.getString("bytesHex"))
            val expectedEncoding = c.getString("expectedEncoding")
            val expectedContent = c.getString("expectedContent")

            assertEquals("[$name] detectEncoding", expectedEncoding, EncodingCodec.detectEncoding(bytes))
            assertEquals("[$name] decodeBytes", expectedContent, EncodingCodec.decodeBytes(bytes, expectedEncoding))

            if (c.optBoolean("expectRoundTrip", false)) {
                val reencoded = EncodingCodec.encodeContent(expectedContent, expectedEncoding)
                assertArrayEquals("[$name] encode(decode(b)) must equal b", bytes, reencoded)
            }
        }
    }

    @Test
    fun unmappableCodepointIsReportedNeverReplaced() {
        // Fixture (iv): typing a non-Latin-1 codepoint into a byte-fidelity
        // document must REPORT/reject with the stable token, never write '?'.
        val cases = fixtures()
        var checked = 0
        for (i in 0 until cases.length()) {
            val c = cases.getJSONObject(i)
            if (!c.optBoolean("expectEncodeReject", false)) continue
            checked++
            val name = c.getString("name")
            val suffix = c.getString("unmappableSuffix")
            val content = c.getString("expectedContent") + suffix
            val encoding = c.getString("expectedEncoding")
            try {
                EncodingCodec.encodeContent(content, encoding)
                fail("[$name] encode must reject unmappable content, not silently write '?'")
            } catch (e: EncodingCodec.EncodingException) {
                assertEquals("[$name] reject must carry the stable token", EncodingCodec.UNMAPPABLE_TOKEN, e.token)
                assertTrue("[$name] message must contain the token", e.message!!.contains(EncodingCodec.UNMAPPABLE_TOKEN))
            }
        }
        assertTrue("at least one unmappable fixture must exist", checked > 0)
    }

    @Test
    fun unknownEncodingLabelIsRejectedOnEncode() {
        // Arbitrary labels crossing the bridge are untrusted input: an unknown
        // label must never be silently written as UTF-8 (the Go default branch).
        try {
            EncodingCodec.encodeContent("hello", "x-user-defined")
            fail("unknown label must be rejected")
        } catch (e: EncodingCodec.EncodingException) {
            assertEquals(EncodingCodec.UNKNOWN_LABEL_TOKEN, e.token)
        }
    }

    @Test
    fun unknownEncodingLabelFallsBackToByteFidelityOnDecode() {
        // decodeBytes with an unknown label returns the byte-fidelity mapping
        // (byte -> same codepoint), never U+FFFD.
        val bytes = byteArrayOf(0xE9.toByte(), 0x41)
        assertEquals("\u00E9A", EncodingCodec.decodeBytes(bytes, "x-user-defined"))
    }

    @Test
    fun invalidUtf8UnderUtf8LabelFallsBackWithoutUfffd() {
        // Defensive: a "utf-8" label paired with invalid bytes must not insert
        // U+FFFD; the byte-fidelity mapping keeps every byte recoverable.
        val bytes = byteArrayOf(0xE9.toByte())
        val decoded = EncodingCodec.decodeBytes(bytes, EncodingCodec.UTF_8)
        assertEquals("\u00E9", decoded)
        assertFalse("no U+FFFD may be inserted", decoded.contains('\uFFFD'))
    }

    @Test
    fun containsCjkMatchesTheGoRanges() {
        assertTrue(EncodingCodec.containsCJK("\u3400"))
        assertTrue(EncodingCodec.containsCJK("\u9FFF"))
        assertTrue(EncodingCodec.containsCJK("\uF900"))
        assertTrue(EncodingCodec.containsCJK("\uFAFF"))
        assertTrue(EncodingCodec.containsCJK("abc\u4E2D"))
        assertFalse(EncodingCodec.containsCJK("plain ascii"))
        assertFalse(EncodingCodec.containsCJK("\u3000\uFF01")) // CJK punctuation is outside the ranges
        assertFalse(EncodingCodec.containsCJK(""))
    }

    // ---- statistical detector seam (the desktop chardet role) ---------------

    /**
     * A GB18030 document whose bytes ALSO strictly decode as Big5 — the exact
     * blind spot of the probe-only path. Measured on the desktop JVM: 5 of 10
     * common simplified GB18030 documents land here, rendering as
     * "斕疑岍賜ㄛ洴岆珨僇…" mojibake when the statistical layer is absent.
     * (The committed fixture corpus happens to contain only the other half —
     * documents the Big5 probe rejects — which is why CI never caught this.)
     */
    private val ambiguousSimplified = "# 使用说明\n\n这是项目的中文说明文档，包含安装步骤和注意事项。"
        .toByteArray(charset("GB18030"))

    @Test
    fun statisticalVerdictOutranksTheStrictProbes() {
        // With a confident statistical layer this document is gb18030, even
        // though the Big5 probe would strictly decode it (the P1 scenario).
        val detected = EncodingCodec.detectEncoding(
            ambiguousSimplified,
        ) { _ -> EncodingCodec.GB18030 }
        assertEquals(EncodingCodec.GB18030, detected)
    }

    @Test
    fun statisticalBig5VerdictOutranksTheProbes() {
        // Symmetric: a Big5 document that also strictly decodes as GB18030
        // must be big5 when the statistics say so.
        val big5Doc = "這是一段繁體中文測試文字，用來驗證統計層的判別。".toByteArray(charset("Big5"))
        assertEquals(EncodingCodec.BIG5, EncodingCodec.detectEncoding(big5Doc) { _ -> EncodingCodec.BIG5 })
    }

    @Test
    fun noStatisticalOpinionFallsThroughToTheProbes() {
        // null / unknown verdicts must not change the probe-only outcome.
        assertEquals(
            "probe-only result",
            EncodingCodec.detectEncoding(ambiguousSimplified),
            EncodingCodec.detectEncoding(ambiguousSimplified) { _ -> null },
        )
        assertEquals(
            "an unrelated ICU verdict (e.g. ISO-8859-x) is no opinion here",
            EncodingCodec.detectEncoding(ambiguousSimplified),
            EncodingCodec.detectEncoding(ambiguousSimplified) { _ -> "ISO-8859-1" },
        )
    }

    @Test
    fun statisticalLayerIsNotConsultedForUtf8OrNulInput() {
        // UTF-8 wins before any detector runs; NUL-containing input never
        // reaches the CJK branch (the Go `bytes.IndexByte(b, 0) == -1` guard).
        val spy = RecordingDetector()
        assertEquals(EncodingCodec.UTF_8, EncodingCodec.detectEncoding("café".toByteArray(), spy))
        assertEquals(
            EncodingCodec.ISO_8859_1,
            EncodingCodec.detectEncoding(byteArrayOf(0x00, 0xE9.toByte()), spy),
        )
        assertEquals("the detector must not run for UTF-8 or NUL input", 0, spy.calls)
    }

    /** Fake detector that counts invocations and always reports no opinion. */
    private class RecordingDetector : EncodingCodec.CharsetStatDetector {
        var calls = 0
        override fun detect(b: ByteArray): String? {
            calls++
            return null
        }
    }

    @Test
    fun decodeCombinedUsesTheStatisticalDetector() {
        val decoded = EncodingCodec.decode(ambiguousSimplified) { _ -> EncodingCodec.GB18030 }
        assertEquals(EncodingCodec.GB18030, decoded.encoding)
        assertArrayEquals(ambiguousSimplified, EncodingCodec.encodeContent(decoded.content, decoded.encoding))
    }

    // ---- the production detector itself ------------------------------------

    /** Documents the OTHER family's strict decoder also accepts: the P1 blind spot. */
    private val ambiguousTraditional = "# 使用說明\n\n這是專案的中文說明文件，包含安裝步驟和注意事項。"
        .toByteArray(charset("Big5"))

    @Test
    fun productionDetectorResolvesAmbiguousSimplifiedDocuments() {
        assertEquals(
            "GB18030 text that also strictly decodes as Big5 must be gb18030",
            EncodingCodec.GB18030,
            CommonHanStatisticDetector.detect(ambiguousSimplified),
        )
    }

    @Test
    fun productionDetectorResolvesAmbiguousTraditionalDocuments() {
        assertEquals(
            "Big5 text that also strictly decodes as GB18030 must be big5",
            EncodingCodec.BIG5,
            CommonHanStatisticDetector.detect(ambiguousTraditional),
        )
    }

    @Test
    fun productionDetectorEndToEndThroughDecode() {
        // The wiring the app actually uses: SafBindings -> decode(bytes, statDetector).
        val d = EncodingCodec.decode(ambiguousSimplified, CommonHanStatisticDetector)
        assertEquals(EncodingCodec.GB18030, d.encoding)
        assertEquals("# 使用说明", d.content.lineSequence().first())
    }

    @Test
    fun productionDetectorHasNoOpinionForUndecidableInput() {
        // Latin-1 byte pairs that neither family strictly decodes: no opinion,
        // the strict probes / byte-fidelity fallback decide.
        assertNull(CommonHanStatisticDetector.detect(byteArrayOf(0xE9.toByte(), 0x41)))
        assertNull(CommonHanStatisticDetector.detect(ByteArray(0)))
    }

    @Test
    fun decodeCombinedFunctionKeepsLabelAndContentConsistent() {
        // detect-then-decode must return a self-consistent pair: the label that
        // produced the content, so a later save cannot corrupt the file.
        val cafe = hexToBytes("636166c3a9")
        val d1 = EncodingCodec.decode(cafe)
        assertEquals(EncodingCodec.UTF_8, d1.encoding)
        assertEquals("café", d1.content)

        val lone = hexToBytes("e9")
        val d2 = EncodingCodec.decode(lone)
        assertEquals(EncodingCodec.ISO_8859_1, d2.encoding)
        assertEquals("\u00E9", d2.content)
    }
}