package io.github.koucpy001.simplify2md.encoding

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Pure-JVM equivalence tests for the newline port (plan todo 9d), driven by the
 * shared static fixture file generated by
 * `android/tools/generate-encoding-fixtures.py`.
 *
 * Mirrors `mdview/app_test.go:145-173`: dominant style wins, an LF file with one
 * stray CRLF keeps LF, and a tie goes to LF.
 */
class NewlineTest {

    private fun fixtures(): JSONObject {
        val stream = requireNotNull(
            NewlineTest::class.java.getResourceAsStream("/encoding/newline-fixtures.json"),
        ) { "missing fixture resource /encoding/newline-fixtures.json" }
        val text = String(stream.readAllBytes(), Charsets.UTF_8)
        return JSONObject(text)
    }

    @Test
    fun detectNewlineMatchesEveryFixture() {
        val cases = fixtures().getJSONArray("cases")
        assertTrue("newline corpus must not be empty", cases.length() > 0)
        for (i in 0 until cases.length()) {
            val c = cases.getJSONObject(i)
            val name = c.getString("name")
            val text = c.getString("text")
            val expected = c.getString("expected")
            assertEquals("[$name] detectNewline", expected, EncodingCodec.detectNewline(text.toByteArray(Charsets.ISO_8859_1)))
        }
    }

    @Test
    fun applyNewlineMatchesEveryFixture() {
        val cases = fixtures().getJSONArray("applyCases")
        assertTrue("apply corpus must not be empty", cases.length() > 0)
        for (i in 0 until cases.length()) {
            val c = cases.getJSONObject(i)
            val name = c.getString("name")
            val content = c.getString("content")
            val newline = c.getString("newline")
            val expected = c.getString("expected")
            assertEquals("[$name] applyNewline", expected, EncodingCodec.applyNewline(content, newline))
        }
    }

    @Test
    fun tieGoesToLf() {
        // Equal CRLF/LF counts: the tie must go to LF (app.go:531-534).
        assertEquals("lf", EncodingCodec.detectNewline("a\r\nb\n".toByteArray(Charsets.ISO_8859_1)))
    }

    @Test
    fun crlfExpansionNormalizesStrayLf() {
        // A CRLF document with one stray LF is fully re-expanded on save.
        assertEquals("a\r\nb\r\nc", EncodingCodec.applyNewline("a\r\nb\nc", "crlf"))
    }
}